# Generated by Django 5.0.1 on 2024-01-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_comment_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
